[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
application.workspace = true
domain.workspace = true
infrastructure.workspace = true
interface.workspace = true

tokio.workspace = true
axum.workspace = true
clap.workspace = true
tracing.workspace = true
anyhow.workspace = true
async-trait.workspace = true


dotenvy = "0.15.7"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
